# Generated by Django 2.2.19 on 2022-12-19 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20221219_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='gpoup',
            new_name='group',
        ),
    ]
